//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бухгалтер
    {
        public int id { get; set; }
        public Nullable<int> выставленныеСчетаСтрахКомпаниями { get; set; }
        public Nullable<int> НаборУслуг { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual users users { get; set; }
        public virtual Выставленые_счета_страховой_компании Выставленые_счета_страховой_компании { get; set; }
    }
}
