//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выставленые_счета_страховой_компании
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Выставленые_счета_страховой_компании()
        {
            this.Бухгалтер = new HashSet<Бухгалтер>();
        }
    
        public int id { get; set; }
        public Nullable<int> Название_страховой_компании { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бухгалтер> Бухгалтер { get; set; }
        public virtual ДанныеСтраховыхКомпаний ДанныеСтраховыхКомпаний { get; set; }
    }
}
