//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные_лаборантов
    {
        public int id { get; set; }
        public Nullable<int> НаборУслуг { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual users users { get; set; }
        public virtual Услуги_лаборатории Услуги_лаборатории { get; set; }
    }
}
