//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДанныеСтраховыхКомпаний
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ДанныеСтраховыхКомпаний()
        {
            this.Выставленые_счета_страховой_компании = new HashSet<Выставленые_счета_страховой_компании>();
            this.Пациент = new HashSet<Пациент>();
        }
    
        public int id { get; set; }
        public string insurance_name { get; set; }
        public string country { get; set; }
        public string insurance_address { get; set; }
        public Nullable<int> insurance_inn { get; set; }
        public string ipadress { get; set; }
        public Nullable<int> insurance_p_c { get; set; }
        public Nullable<int> insurance_bik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выставленые_счета_страховой_компании> Выставленые_счета_страховой_компании { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пациент> Пациент { get; set; }
    }
}
