//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОказаниеУслуг
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ОказаниеУслуг()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int id { get; set; }
        public Nullable<int> service { get; set; }
        public Nullable<double> result { get; set; }
        public Nullable<int> analyzer { get; set; }
        public Nullable<int> user { get; set; }
    
        public virtual Данные_анализатора Данные_анализатора { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual Услуги_лаборатории Услуги_лаборатории { get; set; }
    }
}
