//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пациент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пациент()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<int> passport_s { get; set; }
        public Nullable<int> passport_n { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> social_sec_number { get; set; }
        public string ein { get; set; }
        public Nullable<int> страховая_компания { get; set; }
        public string guid { get; set; }
    
        public virtual ДанныеСтраховыхКомпаний ДанныеСтраховыхКомпаний { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
