//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги_лаборатории
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Услуги_лаборатории()
        {
            this.Данные_лаборантов = new HashSet<Данные_лаборантов>();
            this.ОказаниеУслуг = new HashSet<ОказаниеУслуг>();
        }
    
        public int id { get; set; }
        public string Наименование { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Срок_выполнения { get; set; }
        public Nullable<int> Среднее_отклонение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Данные_лаборантов> Данные_лаборантов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОказаниеУслуг> ОказаниеУслуг { get; set; }
    }
}
